language: node_js
node_js:
- 10.15.3
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY
  secret_access_key: $ACCESS_SECRET
  bucket: "sosrgstudios.com"
  skip_cleanup: true
  acl: public_read
  local_dir: /
  region: ap-south-1